# This workflow sets the test / all status check to success in case it's a docs only PR and main.yml is not triggered
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: main # The name must be the same as in main.yml

on:
  pull_request:
    paths-ignore: # This expression needs to match the paths ignored on main.yml.
      - '!**/*.md'
      - '!**/*.asciidoc'

permissions:
  contents: read

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
